language: minimal


before_install: 
- sudo apt-get update
- sudo apt-get install software-properties-common
- sudo -E apt-add-repository -y  "ppa:ansible/ansible"
- sudo apt-get install ansible

script:
- ansible-playbook --syntax-check CreateProject.yaml
- ansible-playbook CreateProject.yaml